services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:5432"
  
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    env_file:
      - .env

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command: 
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: curl -f http://localhost:9644/v1/status/ready || exit 1
      interval: 5s
      retries: 5
      start_period: 10s

  consumer:
    build:
      context: .
      dockerfile: build/Dockerfile.consumer
    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKER=redpanda:9092
